CREATE TABLE pais(
  idPais INT GENERATED BY default ON NULL AS IDENTITY,
  nombre VARCHAR(45) NOT NULL,
  PRIMARY KEY(idPais)
);

CREATE TABLE usuario(
	correo VARCHAR(60) NOT NULL,
  nombre VARCHAR(40) NOT NULL,
  apellido VARCHAR(40) NOT NULL,
  contrasena VARCHAR(50) NOT NULL,
  fecha_nacimiento DATE NOT NULL,
  foto VARCHAR(100) NOT NULL,
  creditos NUMBER NOT NULL,
  tipo VARCHAR(1) NOT NULL,
  pais_idPais INT NOT NULL,
  CONSTRAINT fk_pais_usuario
    FOREIGN KEY (pais_idPais)
      REFERENCES pais(idPais)
        ON DELETE CASCADE,
  CONSTRAINT pk_usuario
    PRIMARY KEY (correo,pais_idPais)
);

CREATE TABLE chat(
	idChat INT GENERATED BY default ON NULL AS IDENTITY, 
  FECHA DATE NOT NULL,
  PRIMARY KEY (idChat)
);

CREATE TABLE mensaje (
	idMensaje INT GENERATED BY default ON NULL AS IDENTITY, 
  mensaje VARCHAR(150) NOT NULL,
  hora TIMESTAMP NOT NULL,
  chat_idChat INT NOT NULL,
  CONSTRAINT fk_chat_mensaje 
    FOREIGN KEY (chat_idChat) 
      REFERENCES chat(idChat) 
        ON DELETE CASCADE,
  CONSTRAINT pk_mensaje 
  PRIMARY KEY (idMensaje,chat_idChat)
);

CREATE TABLE chat_de_usuario(
	usuario_correo VARCHAR(60) NOT NULL,
  usuario_pais_idPais INT NOT NULL,
  chat_idChat INT NOT NULL,
  CONSTRAINT fk_usuario_chat
    FOREIGN KEY (usuario_correo,usuario_pais_idPais)
      REFERENCES usuario(correo,pais_idPais)
        ON DELETE CASCADE,
  CONSTRAINT fk_chat_usuario
    FOREIGN KEY (chat_idChat)
      REFERENCES chat(idChat)
        ON DELETE CASCADE,
  CONSTRAINT pk_chat_de_usuario
    PRIMARY KEY (usuario_correo,chat_idChat)
);

CREATE TABLE tipo_accion(
	idTipoAccion INT GENERATED BY default ON NULL AS IDENTITY,
  tipo VARCHAR(45) NOT NULL,
  PRIMARY KEY (idTipoAccion)
);

CREATE TABLE accion(
  idAccion INT GENERATED BY default ON NULL AS IDENTITY,
  descripcion VARCHAR(50) NOT NULL,
  fecha_hora TIMESTAMP NOT NULL,
  usuario_correo VARCHAR(60) NOT NULL,
  usuario_pais_idPais INT NOT NULL,
  tipo_accion_idTipoAccion INT NOT NULL,
  CONSTRAINT fk_accion_usuario
    FOREIGN KEY (usuario_correo,usuario_pais_idPais)
      REFERENCES usuario(correo,pais_idPais)
        ON DELETE CASCADE,
  CONSTRAINT fk_tipo_accion
    FOREIGN KEY (tipo_accion_idTipoAccion)
      REFERENCES tipo_accion(idTipoAccion)
        ON DELETE CASCADE,
  CONSTRAINT pk_accion
    PRIMARY KEY (idAccion,usuario_correo,usuario_pais_idPais,tipo_accion_idTipoAccion)
);

CREATE TABLE categoria(
	idCategoria INT GENERATED BY default ON NULL AS IDENTITY,
  nombre VARCHAR(45),
  PRIMARY KEY (idCategoria)
);

CREATE TABLE producto(
	idProducto INT GENERATED BY default ON NULL AS IDENTITY,
  nombre VARCHAR(50) NOT NULL,
  descripcion VARCHAR(150) NOT NULL,
  precio NUMBER NOT NULL,
  megusta INT NOT NULL,
  nomegusta INT NOT NULL,
  categoria_idCategoria INT NOT NULL,
  usuario_correo VARCHAR(60) NOT NULL,
  usuario_pais_idPais INT NOT NULL,
  cantidad INT NOT NULL,
  CONSTRAINT fk_producto_categoria
    FOREIGN KEY (categoria_idCategoria)
      REFERENCES categoria(idCategoria)
        ON DELETE CASCADE,
  CONSTRAINT fk_producto_usuario
    FOREIGN KEY (usuario_correo,usuario_pais_idPais)
      REFERENCES usuario(correo,pais_idPais)
        ON DELETE CASCADE,
  CONSTRAINT pk_producto
    PRIMARY KEY (idProducto,categoria_idCategoria,usuario_correo,usuario_pais_idPais)
);

CREATE TABLE denuncia(
  idDenuncia INT GENERATED BY default ON NULL AS IDENTITY,
  detalle VARCHAR(150) NOT NULL,
  producto_idProducto INT NOT NULL,
  producto_categoria_idCategoria INT NOT NULL,
  producto_usuario_correo VARCHAR(60) NOT NULL,
  producto_usuario_pais_idPais INT NOT NULL,
  fecha TIMESTAMP NOT NULL,
  CONSTRAINT fk_denuncia_producto
    FOREIGN KEY (producto_idProducto,producto_categoria_idCategoria,producto_usuario_correo,producto_usuario_pais_idPais)
      REFERENCES producto(idProducto,categoria_idCategoria,usuario_correo,usuario_pais_idPais)
        ON DELETE CASCADE,
  CONSTRAINT pk_denuncia
    PRIMARY KEY (idDenuncia,producto_idProducto,producto_categoria_idCategoria,producto_usuario_correo,producto_usuario_pais_idPais)
);

CREATE TABLE comentario(
	idComentario INT GENERATED BY default ON NULL AS IDENTITY,
  detalle VARCHAR(150) NOT NULL,
  producto_idProducto INT NOT NULL,
  producto_categoria_idCategoria INT NOT NULL,
  producto_usuario_correo VARCHAR(60) NOT NULL,
  producto_usuario_pais_idPais INT NOT NULL,
  fecha TIMESTAMP NOT NULL,
  CONSTRAINT fk_comentario_producto
  	FOREIGN KEY (producto_idProducto,producto_categoria_idCategoria,producto_usuario_correo,producto_usuario_pais_idPais)
  		REFERENCES producto(idProducto,categoria_idCategoria,usuario_correo,usuario_pais_idPais)
  			ON DELETE CASCADE,
  CONSTRAINT pk_comentario
  	PRIMARY KEY (idComentario,producto_idProducto,producto_categoria_idCategoria,producto_usuario_correo,producto_usuario_pais_idPais)
);

CREATE TABLE palabra_clave(
	idPalabraClave INT GENERATED BY default ON NULL AS IDENTITY,
  palabra VARCHAR(45) NOT NULL,
  PRIMARY KEY (idPalabraClave)
);

CREATE TABLE palabra_clave_de_producto(
	producto_idProducto INT NOT NULL,
  producto_categoria_idCategoria INT NOT NULL,
  producto_usuario_correo VARCHAR(60) NOT NULL,
  producto_usuario_pais_idPais INT NOT NULL,
  palabra_clave_idPalabraClave INT NOT NULL,
  CONSTRAINT fk_palabraclaveproducto_producto
    FOREIGN KEY (producto_idProducto,producto_categoria_idCategoria,producto_usuario_correo,producto_usuario_pais_idPais)
      REFERENCES producto(idProducto,categoria_idCategoria,usuario_correo,usuario_pais_idPais)
        ON DELETE CASCADE,
  CONSTRAINT fk_plabraclaveproducto_palabra_clave
    FOREIGN KEY (palabra_clave_idPalabraClave)
      REFERENCES palabra_clave(idPalabraclave)
        ON DELETE CASCADE,
  CONSTRAINT pk_palabraclaveproducto
    PRIMARY KEY (producto_idProducto,producto_categoria_idCategoria,producto_usuario_correo,producto_usuario_pais_idPais,palabra_clave_idPalabraClave)
);

CREATE TABLE carrito(
	idCarrito INT GENERATED BY default ON NULL AS IDENTITY,
  total NUMBER NOT NULL,
  usuario_correo VARCHAR(60) NOT NULL,
  usuario_pais_idPais INT NOT NULL,
  CONSTRAINT fk_carrito_usuario
    FOREIGN KEY (usuario_correo,usuario_pais_idPais)
      REFERENCES usuario(correo,pais_idPais)
        ON DELETE CASCADE,
  CONSTRAINT pk_carrito
    PRIMARY KEY (idCarrito,usuario_correo,usuario_pais_idPais)
);

CREATE TABLE producto_en_carrito(
	producto_idProducto INT NOT NULL,
  producto_categoria_idCategoria INT NOT NULL,
  producto_usuario_correo VARCHAR(60) NOT NULL,
  producto_usuario_pais_idPais INT NOT NULL,
  carrito_idCarrito INT NOT NULL,
  carrito_usuario_correo VARCHAR(60) NOT NULL,
  carrito_usuario_pais_idPais INT NOT NULL,
  cantidad INT NOT NULL,
  CONSTRAINT fk_pec_producto
    FOREIGN KEY (producto_idProducto,producto_categoria_idCategoria,producto_usuario_correo,producto_usuario_pais_idPais)
      REFERENCES producto(idProducto,categoria_idCategoria,usuario_correo,usuario_pais_idPais)
        ON DELETE CASCADE,
  CONSTRAINT fk_pec_carrito
    FOREIGN KEY (carrito_idCarrito,carrito_usuario_correo,carrito_usuario_pais_idPais)
      REFERENCES carrito(idCarrito,usuario_correo,usuario_pais_idPais)
        ON DELETE CASCADE,
  CONSTRAINT pk_pec
    PRIMARY KEY (producto_idProducto,producto_categoria_idCategoria,producto_usuario_correo,producto_usuario_pais_idPais,carrito_idCarrito,carrito_usuario_correo,carrito_usuario_pais_idPais)
);

CREATE TABLE compra(
	idCompra INT GENERATED BY default ON NULL AS IDENTITY,
  fecha TIMESTAMP NOT NULL,
  carrito_idCarrito INT NOT NULL,
  carrito_usuario_correo VARCHAR(60) NOT NULL,
  carrito_usuario_pais_idPais INT NOT NULL,
  CONSTRAINT fk_compra_carrito
    FOREIGN KEY (carrito_idCarrito,carrito_usuario_correo,carrito_usuario_pais_idPais)
      REFERENCES carrito(idCarrito,usuario_correo,usuario_pais_idPais)
        ON DELETE CASCADE,
  CONSTRAINT pk_compra
    PRIMARY KEY (idCompra, carrito_idCarrito,carrito_usuario_correo,carrito_usuario_pais_idPais)
);

